name: image_picker
description: An image picker flugin
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: image_picker_android
      ios:
        default_package: image_picker_ios





dependencies:
  flutter:
    sdk: flutter
  image_picker_android:
#    path: ../image_picker_android
    git:
      url: https://github.com/hoanghn418/image_picker.git
      path: image_picker_android
      ref: use-package-from-git-repo
  image_picker_ios:
#    path: ../image_picker_ios
    git:
      url: https://github.com/hoanghn418/image_picker.git
      path: image_picker_ios
      ref: use-package-from-git-repo




  image_picker_platform_interface:
#    path: ../image_picker_platform_interface
    git:
      url: https://github.com/hoanghn418/image_picker.git
      path: image_picker_platform_interface
      ref: use-package-from-git-repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  plugin_platform_interface: ^2.0.1
  very_good_analysis: ^2.4.0
