name: image_picker_platform_interface
description: A common platform interface for the image_picker plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  very_good_analysis: ^2.4.0
